### PR TITLE
datepicker: use a native input to show the selected value

### LINKED ISSUE #106: proposal(datepicker): use native input element
This issue is a proposal to change the span that shows the current value from the datepicker to use a native input from the browser. 

From:
`<span class="md2-datepicker-input-text">{{_viewValue}}</span>` 

To something like:
`<input [(ngModel)]="_viewValue" [required]="required" disabled class="md2-datepicker-input-text" />`

With this change, we can use the native form validation from the browser on the datepicker

### PR DESCRIPTION
**Pull request by jefersonestevo**
Fixes #106

### CODE REVIEW

**Comment by dharmeshpipariya-zz** [comment]
@jefersonestevo please rebase it and resolve conflicts, also use input type according to the type of picker (i.e. date, time, datetime)

**Comment by jefersonestevo** [comment]
@dharmeshpipariya I've resolved the conflicts in this branch. The only thing is that I haven't changed the input type because I couldn't find a good way to disable chrome native datepicker, and it causes conflicts with this one.

**Comment by dharmeshpipariya-zz** [comment]
@jefersonestevo , your input is not working properly as well as it is not reflect two way modal binding and events.

**Comment by dharmeshpipariya-zz** [comment]
@jefersonestevo thanks for the PR, but we have implemented it in another way so we close this PR.

**Pull request closed without merging**
